// Code generated by "stringer -type=ObjectType -linecomment"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTUnknown-0]
	_ = x[OTNode-1]
	_ = x[OTPod-2]
	_ = x[OTNamespace-3]
}

const _ObjectType_name = "UnknownNodePodNamespace"

var _ObjectType_index = [...]uint8{0, 7, 11, 14, 23}

func (i ObjectType) String() string {
	if i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
