// Code generated by "stringer -type=ChangeType"; DO NOT EDIT.

package reader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CTUnknown-0]
	_ = x[CTAdd-1]
	_ = x[CTUpdate-2]
	_ = x[CTDelete-3]
}

const _ChangeType_name = "CTUnknownCTAddCTUpdateCTDelete"

var _ChangeType_index = [...]uint8{0, 9, 14, 22, 30}

func (i ChangeType) String() string {
	if i >= ChangeType(len(_ChangeType_index)-1) {
		return "ChangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
