// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package reader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DTUnknown-0]
	_ = x[DTNode-1]
	_ = x[DTPod-2]
	_ = x[DTNamespace-3]
}

const _DataType_name = "DTUnknownDTNodeDTPodDTNamespace"

var _DataType_index = [...]uint8{0, 9, 15, 20, 31}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
